<?php

namespace Database\Seeders;

use App\Http\Middleware\Company;
use App\Models\Branch;
use App\Models\Company as ModelsCompany;
use App\Models\Contract;
use App\Models\Department;
use App\Models\Designation;
use App\Models\Plan;
use App\Models\Status;
use App\Models\Type;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrPermissions = [
            [
                'name' => 'manage attendance-overview',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'mod_id' => 1,
            ],
            [
                'name' => 'manage employee ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create employee ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'show employee ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit employee ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete employee ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage salary',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage payslips',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create salary',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create allowance ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit allowance ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete allowance ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create commission',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit commission',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete commission',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create loan ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit loan ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete loan ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create deduction ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit deduction ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete deduction ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create otherpayments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit otherpayments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete otherpayments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage leaves',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create leaves',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit leaves',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete leaves',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage trainer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create trainer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit trainer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete trainer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage traininglist',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create traininglist',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'show traininglist',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit traininglist',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete traininglist',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage training-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create training-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit training-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage hradminsetup',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage transfer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create transfer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit transfer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete transfer',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage promotions',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create promotions',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit promotions',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete promotions',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage awards',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create awards',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit awards',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete awards',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage resignation',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create resignation',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit resignation',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete resignation',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage termination',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create termination',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit termination',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete termination',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage complaints',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create complaints',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit complaints',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete complaints',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage holidays',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create holidays',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit holidays',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete holidays',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage recruitments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage jobs',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create jobs',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit jobs',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete jobs',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage candidates',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create candidates',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit candidates',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete candidates',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage interviewschedule',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create interviewschedule',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit interviewschedule',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete interviewschedule',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage employee-assets',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'show employee-assets',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create employee-assets',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit employee-assets',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete employee-assets',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage notice-board',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create notice-board',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit notice-board',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete notice-board',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage events',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create events',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit events',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete events',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage settings',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage departments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create departments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit departments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete departments',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage designations',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create designations',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit designations',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete designations',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage leave-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create leave-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit leave-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete leave-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage assets ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create assets ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit assets ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete assets ',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage contract-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create contract-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit contract-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete contract-types',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage gifts',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create gifts',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit gifts',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete gifts',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage award-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create award-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit award-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete award-type',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage payslip-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create payslip-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit payslip-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete payslip-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage allowance-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create allowance-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit allowance-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete allowance-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage loan-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create loan-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit loan-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete loan-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage deduction-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create deduction-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit deduction-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'delete deduction-options',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage user-management',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage role',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create role',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit role',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage ip-restriction',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create ip-restriction',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit ip-restriction',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'manage attendance-timeslots',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'create attendance-timeslots',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
            [
                'name' => 'edit attendance-timeslots',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                 'mod_id' => 1,
            ],
        ];


        Permission::insert($arrPermissions);

        Plan::create([
            'name' => 'Gold',
            'price' => 7000,
            'duration' => 'Monthly',
            'description' => 'test',
            'hrm' => 1,
            'created_by' => 1,
        ]);
    }   
}
